# Datasets:

## Library Installs and Imports

In [1]:
%pip install requests numpy pandas matplotlib
import requests, numpy as np, pandas as pd

Requirement already satisfied: requests in c:\Users\bubs5\OneDrive\Documents\GitHub\Demo-Projects\.venv\Lib\site-packages (2.34.2)
Requirement already satisfied: numpy in c:\Users\bubs5\OneDrive\Documents\GitHub\Demo-Projects\.venv\Lib\site-packages (2.5.3)
Requirement already satisfied: pandas in c:\Users\bubs5\OneDrive\Documents\GitHub\Demo-Projects\.venv\Lib\site-packages (3.0.6)
Requirement already satisfied: matplotlib in c:\Users\bubs5\OneDrive\Documents\GitHub\Demo-Projects\.venv\Lib\site-packages (3.11.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\bubs5\OneDrive\Documents\GitHub\Demo-Projects\.venv\Lib\site-packages (from requests) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\bubs5\OneDrive\Documents\GitHub\Demo-Projects\.venv\Lib\site-packages (from requests) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\bubs5\OneDrive\Documents\GitHub\Demo-Projects\.venv\Lib\site-packages (from requests) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\bubs5\OneDrive\Documents\GitHub\Demo-Projects\.venv\Lib\site-packages (from requests) (2026.7.22)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\bubs5\OneDrive\Documents\GitHub\Demo-Projects\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\bubs5\OneDrive\Documents\GitHub\Demo-Projects\.venv\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\bubs5\OneDrive\Documents\GitHub\Demo-Projects\.venv\Lib\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\Users\bubs5\OneDrive\Documents\GitHub\Demo-Projects\.venv\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\bubs5\OneDrive\Documents\GitHub\Demo-Projects\.venv\Lib\site-packages (from matplotlib) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\bubs5\OneDrive\Documents\GitHub\Demo-Projects\.venv\Lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in c:\Users\bubs5\OneDrive\Documents\GitHub\Demo-Projects\.venv\Lib\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in c:\Users\bubs5\OneDrive\Documents\GitHub\Demo-Projects\.venv\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\bubs5\OneDrive\Documents\GitHub\Demo-Projects\.venv\Lib\site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: six>=1.5 in c:\Users\bubs5\OneDrive\Documents\GitHub\Demo-Projects\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

## Collecting Data

### Biking Data

In [2]:
###get biking data 
bridge_url = 'https://data.seattle.gov/api/v3/views/65db-xm6k/query.json'
r = requests.get(bridge_url).json()

In [3]:
###initially process data 
###drop irrelevant information, convert time to datetime object
bike_df = pd.DataFrame(r).drop(columns=[':id',':version',':updated_at',':created_at'])

###converting date to timezone aware 
is_dst = ~bike_df['date'].duplicated(keep='first')
bike_df.date = pd.to_datetime(bike_df.date, format='%Y-%m-%dT%H:%M:%S.%f').dt.tz_localize('America/Los_Angeles', ambiguous=is_dst, nonexistent='NaT')

#convert strings to floats 
num_cols = bike_df.select_dtypes(str).columns.to_list()
bike_df[num_cols] = bike_df[num_cols].apply(lambda x: pd.to_numeric(x), axis=0)

###dropping nan dates
bike_df = bike_df.dropna(subset='date')

####dropping nan bike counts, will eventually impute data by local average
bike_df = bike_df.dropna()

In [4]:
print('10 highest Days:\n_____________________')
bike_df.sort_values('fremont_bridge', ascending=False)[:10]

10 highest Days:
_____________________

,date,fremont_bridge,fremont_bridge_nb,fremont_bridge_sb
63318,2019-06-11 17:00:00-07:00,1097.0,850.0,247.0
61470,2019-08-27 17:00:00-07:00,1071.0,826.0,245.0
62982,2019-06-25 17:00:00-07:00,1052.0,795.0,257.0
63798,2019-05-22 17:00:00-07:00,1004.0,745.0,259.0
61806,2019-08-13 17:00:00-07:00,998.0,780.0,218.0
61278,2019-09-04 17:00:00-07:00,997.0,790.0,207.0
63486,2019-06-04 17:00:00-07:00,995.0,742.0,253.0
63342,2019-06-10 17:00:00-07:00,993.0,765.0,228.0
61782,2019-08-14 17:00:00-07:00,989.0,737.0,252.0
61110,2019-09-11 17:00:00-07:00,983.0,768.0,215.0

In [5]:
####save data to csv 
bike_df.to_csv('scraped_data/fremont_bridge_counter.csv', index=False)

### Weather Data

In [1]:
###set up weather data api 

import os, requests, pandas as pd, time, json 

API_key = os.getenv('weather-api')
lat, lon = [47.61191234063561, -122.33851982527909]
units = 'imperial'

####get historical weather data for period the fremont bridge counter is active 
from datetime import datetime
###set start date to unix version of fremont bridge csv
start = bike_df.date.min().timestamp().__int__()
end = bike_df.date.max().timestamp().__int__()


print('We will need to make ', np.round((end-start)/3600/20).__int__(), ' calls total.')

NameError: name 'bike_df' is not defined

In [ ]:
prev_records = pd.read_csv('scraped_data/weather.csv')

,dt,temp,feels_like,pressure,humidity,dew_point,uvi,clouds,visibility,wind_speed,wind_deg,wind_gust,date,weather_main,weather_desc,rain_1hr_mm,snow_1hr_mm
0,1349182800,52.93,51.35,1022,73,44.53,0,31,10000,11.50,180,18.39,2012-10-02 06:00:00-07:00,Clouds,scattered clouds,0.0,0.0
1,1349186400,53.04,51.71,1022,78,46.38,0,29,10000,10.36,180,12.64,2012-10-02 07:00:00-07:00,Clouds,scattered clouds,0.0,0.0
2,1349190000,54.52,52.63,1022,63,42.21,0,30,10000,11.50,180,19.55,2012-10-02 08:00:00-07:00,Clouds,scattered clouds,0.0,0.0
3,1349193600,55.63,53.44,1022,54,39.27,0,29,10000,6.89,180,10.36,2012-10-02 09:00:00-07:00,Clouds,scattered clouds,0.0,0.0
4,1349197200,57.25,55.26,1022,55,41.25,0,43,10000,4.61,180,8.05,2012-10-02 10:00:00-07:00,Clouds,scattered clouds,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121957,1788228000,68.76,68.43,1008,66,56.95,0,90,10000,5.99,17,8.99,2026-08-31 19:00:00-07:00,Clouds,overcast clouds,0.0,0.0
121958,1788231600,66.33,65.80,1008,67,55.06,0,72,10000,7.00,338,8.01,2026-08-31 20:00:00-07:00,Clouds,broken clouds,0.0,0.0
121959,1788235200,64.56,63.82,1008,66,52.97,0,12,10000,3.27,6,NaN,2026-08-31 21:00:00-07:00,Clouds,few clouds,0.0,0.0
121960,1788238800,63.72,63.09,1009,70,53.76,0,7,10000,1.01,285,1.99,2026-08-31 22:00:00-07:00,Clear,clear sky,0.0,0.0
121961,1788242400,62.78,62.19,1008,73,54.01,0,8,10000,1.01,274,1.99,2026-08-31 23:00:00-07:00,Clear,clear sky,0.0,0.0

In [7]:
###loop to get data from start time to end time, not the most efficient but it works for now 
weather_data = pd.DataFrame()
CHECKPOINT = 'scraped_data/weather_checkpoint.pkl'

###check if there is a more recent checkpoint to start off from 
if os.path.exists(CHECKPOINT):
    records = pd.read_pickle(CHECKPOINT).to_dict('records')
    start = (max(rec['dt'] for rec in records) + 1 ).__int__()
    print(f'Resuming from {datetime.fromtimestamp(start)} - {len(records)} hours of data already saved.')
else:
    records = []
    start = bike_df.date.min().timestamp().__int__()

###initialization
weather_url = f'https://api.openweathermap.org/data/4.0/onecall/timeline/1h?lat={lat}&lon={lon}&units={units}&start={start}&appid={API_key}'
calls = 0
max_calls = 1200
session = requests.Session()

try:
    while weather_url and start < end:

        print('Data is within range. Requesting...')
        resp = session.get(weather_url, timeout=30)
        resp.raise_for_status()
        r = resp.json()

    ##if no response, break 
        batch = r.get('data', [])
        if not batch:   
            break
        
        records.extend(batch)
        calls += 1

        ###ends when date end is reached 
        if batch[-1]['dt'] >= end:
            break 

        ###save every 20 calls just in case 
        if calls % 20 == 0:
            pd.DataFrame(records).to_pickle(CHECKPOINT)
        data_time = datetime.fromtimestamp(r['data'][0]['dt'])

        ###break at 1000 calls - free daily limit  
        if calls == max_calls:
            break

        print(f'Data Saved for {data_time} - Call: {calls}')

        weather_url = r.get('next')
        time.sleep(1)
except requests.HTTPError:
    print('\nReached max calls for the day! Try again tomorrow.\n')
finally:
    pd.DataFrame(records).to_pickle(CHECKPOINT)
    print(f'{len(records)} hourly records saved. ')

Resuming from 2025-06-10 09:00:01 - 111220 hours of data already saved.
Data is within range. Requesting...
Data Saved for 2025-06-10 10:00:00 - Call: 1
Data is within range. Requesting...
Data Saved for 2025-06-11 06:00:00 - Call: 2
Data is within range. Requesting...
Data Saved for 2025-06-12 02:00:00 - Call: 3
Data is within range. Requesting...
Data Saved for 2025-06-12 22:00:00 - Call: 4
Data is within range. Requesting...
Data Saved for 2025-06-13 18:00:00 - Call: 5
Data is within range. Requesting...
Data Saved for 2025-06-14 14:00:00 - Call: 6
Data is within range. Requesting...
Data Saved for 2025-06-15 10:00:00 - Call: 7
Data is within range. Requesting...
Data Saved for 2025-06-16 06:00:00 - Call: 8
Data is within range. Requesting...
Data Saved for 2025-06-17 02:00:00 - Call: 9
Data is within range. Requesting...
Data Saved for 2025-06-17 22:00:00 - Call: 10
Data is within range. Requesting...
Data Saved for 2025-06-18 18:00:00 - Call: 11
Data is within range. Requesting...
Data Saved for 2025-06-19 14:00:00 - Call: 12
Data is within range. Requesting...
Data Saved for 2025-06-20 10:00:00 - Call: 13
Data is within range. Requesting...
Data Saved for 2025-06-21 06:00:00 - Call: 14
Data is within range. Requesting...
Data Saved for 2025-06-22 02:00:00 - Call: 15
Data is within range. Requesting...
Data Saved for 2025-06-22 22:00:00 - Call: 16
Data is within range. Requesting...
Data Saved for 2025-06-23 18:00:00 - Call: 17
Data is within range. Requesting...
Data Saved for 2025-06-24 14:00:00 - Call: 18
Data is within range. Requesting...
Data Saved for 2025-06-25 10:00:00 - Call: 19
Data is within range. Requesting...
Data Saved for 2025-06-26 06:00:00 - Call: 20
Data is within range. Requesting...
Data Saved for 2025-06-27 02:00:00 - Call: 21
Data is within range. Requesting...
Data Saved for 2025-06-27 22:00:00 - Call: 22
Data is within range. Requesting...
Data Saved for 2025-06-28 18:00:00 - Call: 23
Data is within range. Requesting...
Data Saved for 2025-06-29 14:00:00 - Call: 24
Data is within range. Requesting...
Data Saved for 2025-06-30 10:00:00 - Call: 25
Data is within range. Requesting...
Data Saved for 2025-07-01 06:00:00 - Call: 26
Data is within range. Requesting...
Data Saved for 2025-07-02 02:00:00 - Call: 27
Data is within range. Requesting...
Data Saved for 2025-07-02 22:00:00 - Call: 28
Data is within range. Requesting...
Data Saved for 2025-07-03 18:00:00 - Call: 29
Data is within range. Requesting...
Data Saved for 2025-07-04 14:00:00 - Call: 30
Data is within range. Requesting...
Data Saved for 2025-07-05 10:00:00 - Call: 31
Data is within range. Requesting...
Data Saved for 2025-07-06 06:00:00 - Call: 32
Data is within range. Requesting...
Data Saved for 2025-07-07 02:00:00 - Call: 33
Data is within range. Requesting...
Data Saved for 2025-07-07 22:00:00 - Call: 34
Data is within range. Requesting...
Data Saved for 2025-07-08 18:00:00 - Call: 35
Data is within range. Requesting...
Data Saved for 2025-07-09 14:00:00 - Call: 36
Data is within range. Requesting...
Data Saved for 2025-07-10 10:00:00 - Call: 37
Data is within range. Requesting...
Data Saved for 2025-07-11 06:00:00 - Call: 38
Data is within range. Requesting...
Data Saved for 2025-07-12 02:00:00 - Call: 39
Data is within range. Requesting...
Data Saved for 2025-07-12 22:00:00 - Call: 40
Data is within range. Requesting...
Data Saved for 2025-07-13 18:00:00 - Call: 41
Data is within range. Requesting...
Data Saved for 2025-07-14 14:00:00 - Call: 42
Data is within range. Requesting...
Data Saved for 2025-07-15 10:00:00 - Call: 43
Data is within range. Requesting...
Data Saved for 2025-07-16 06:00:00 - Call: 44
Data is within range. Requesting...
Data Saved for 2025-07-17 02:00:00 - Call: 45
Data is within range. Requesting...
Data Saved for 2025-07-17 22:00:00 - Call: 46
Data is within range. Requesting...
Data Saved for 2025-07-18 18:00:00 - Call: 47
Data is within range. Requesting...
Data Saved for 2025-07-19 14:00:00 - Call: 48
Data is within range. Requesting...
Data Saved for 2025-07-20 10:00:00 - Call: 49
Data is within range. Requesting...
Data Saved for 2025-07-21 06:00:00 - Call: 50
Data is within range. Requesting...
Data Saved for 2025-07-22 02:00:00 - Call: 51
Data is within range. Requesting...
Data Saved for 2025-07-22 22:00:00 - Call: 52
Data is within range. Requesting...
Data Saved for 2025-07-23 18:00:00 - Call: 53
Data is within range. Requesting...
Data Saved for 2025-07-24 14:00:00 - Call: 54
Data is within range. Requesting...
Data Saved for 2025-07-25 10:00:00 - Call: 55
Data is within range. Requesting...
Data Saved for 2025-07-26 06:00:00 - Call: 56
Data is within range. Requesting...
Data Saved for 2025-07-27 02:00:00 - Call: 57
Data is within range. Requesting...
Data Saved for 2025-07-27 22:00:00 - Call: 58
Data is within range. Requesting...
Data Saved for 2025-07-28 18:00:00 - Call: 59
Data is within range. Requesting...
Data Saved for 2025-07-29 14:00:00 - Call: 60
Data is within range. Requesting...
Data Saved for 2025-07-30 10:00:00 - Call: 61
Data is within range. Requesting...
Data Saved for 2025-07-31 06:00:00 - Call: 62
Data is within range. Requesting...
Data Saved for 2025-08-01 02:00:00 - Call: 63
Data is within range. Requesting...
Data Saved for 2025-08-01 22:00:00 - Call: 64
Data is within range. Requesting...
Data Saved for 2025-08-02 18:00:00 - Call: 65
Data is within range. Requesting...
Data Saved for 2025-08-03 14:00:00 - Call: 66
Data is within range. Requesting...
Data Saved for 2025-08-04 10:00:00 - Call: 67
Data is within range. Requesting...
Data Saved for 2025-08-05 06:00:00 - Call: 68
Data is within range. Requesting...
Data Saved for 2025-08-06 02:00:00 - Call: 69
Data is within range. Requesting...
Data Saved for 2025-08-06 22:00:00 - Call: 70
Data is within range. Requesting...
Data Saved for 2025-08-07 18:00:00 - Call: 71
Data is within range. Requesting...
Data Saved for 2025-08-08 14:00:00 - Call: 72
Data is within range. Requesting...
Data Saved for 2025-08-09 10:00:00 - Call: 73
Data is within range. Requesting...
Data Saved for 2025-08-10 06:00:00 - Call: 74
Data is within range. Requesting...
Data Saved for 2025-08-11 02:00:00 - Call: 75
Data is within range. Requesting...
Data Saved for 2025-08-11 22:00:00 - Call: 76
Data is within range. Requesting...
Data Saved for 2025-08-12 18:00:00 - Call: 77
Data is within range. Requesting...
Data Saved for 2025-08-13 14:00:00 - Call: 78
Data is within range. Requesting...
Data Saved for 2025-08-14 10:00:00 - Call: 79
Data is within range. Requesting...
Data Saved for 2025-08-15 06:00:00 - Call: 80
Data is within range. Requesting...
Data Saved for 2025-08-16 02:00:00 - Call: 81
Data is within range. Requesting...
Data Saved for 2025-08-16 22:00:00 - Call: 82
Data is within range. Requesting...
Data Saved for 2025-08-17 18:00:00 - Call: 83
Data is within range. Requesting...
Data Saved for 2025-08-18 14:00:00 - Call: 84
Data is within range. Requesting...
Data Saved for 2025-08-19 10:00:00 - Call: 85
Data is within range. Requesting...
Data Saved for 2025-08-20 06:00:00 - Call: 86
Data is within range. Requesting...
Data Saved for 2025-08-21 02:00:00 - Call: 87
Data is within range. Requesting...
Data Saved for 2025-08-21 22:00:00 - Call: 88
Data is within range. Requesting...
Data Saved for 2025-08-22 18:00:00 - Call: 89
Data is within range. Requesting...
Data Saved for 2025-08-23 14:00:00 - Call: 90
Data is within range. Requesting...
Data Saved for 2025-08-24 10:00:00 - Call: 91
Data is within range. Requesting...
Data Saved for 2025-08-25 06:00:00 - Call: 92
Data is within range. Requesting...
Data Saved for 2025-08-26 02:00:00 - Call: 93
Data is within range. Requesting...
Data Saved for 2025-08-26 22:00:00 - Call: 94
Data is within range. Requesting...
Data Saved for 2025-08-27 18:00:00 - Call: 95
Data is within range. Requesting...
Data Saved for 2025-08-28 14:00:00 - Call: 96
Data is within range. Requesting...
Data Saved for 2025-08-29 10:00:00 - Call: 97
Data is within range. Requesting...
Data Saved for 2025-08-30 06:00:00 - Call: 98
Data is within range. Requesting...
Data Saved for 2025-08-31 02:00:00 - Call: 99
Data is within range. Requesting...
Data Saved for 2025-08-31 22:00:00 - Call: 100
Data is within range. Requesting...
Data Saved for 2025-09-01 18:00:00 - Call: 101
Data is within range. Requesting...
Data Saved for 2025-09-02 14:00:00 - Call: 102
Data is within range. Requesting...
Data Saved for 2025-09-03 10:00:00 - Call: 103
Data is within range. Requesting...
Data Saved for 2025-09-04 06:00:00 - Call: 104
Data is within range. Requesting...
Data Saved for 2025-09-05 02:00:00 - Call: 105
Data is within range. Requesting...
Data Saved for 2025-09-05 22:00:00 - Call: 106
Data is within range. Requesting...
Data Saved for 2025-09-06 18:00:00 - Call: 107
Data is within range. Requesting...
Data Saved for 2025-09-07 14:00:00 - Call: 108
Data is within range. Requesting...
Data Saved for 2025-09-08 10:00:00 - Call: 109
Data is within range. Requesting...
Data Saved for 2025-09-09 06:00:00 - Call: 110
Data is within range. Requesting...
Data Saved for 2025-09-10 02:00:00 - Call: 111
Data is within range. Requesting...
Data Saved for 2025-09-10 22:00:00 - Call: 112
Data is within range. Requesting...
Data Saved for 2025-09-11 18:00:00 - Call: 113
Data is within range. Requesting...
Data Saved for 2025-09-12 14:00:00 - Call: 114
Data is within range. Requesting...
Data Saved for 2025-09-13 10:00:00 - Call: 115
Data is within range. Requesting...
Data Saved for 2025-09-14 06:00:00 - Call: 116
Data is within range. Requesting...
Data Saved for 2025-09-15 02:00:00 - Call: 117
Data is within range. Requesting...
Data Saved for 2025-09-15 22:00:00 - Call: 118
Data is within range. Requesting...
Data Saved for 2025-09-16 18:00:00 - Call: 119
Data is within range. Requesting...
Data Saved for 2025-09-17 14:00:00 - Call: 120
Data is within range. Requesting...
Data Saved for 2025-09-18 10:00:00 - Call: 121
Data is within range. Requesting...
Data Saved for 2025-09-19 06:00:00 - Call: 122
Data is within range. Requesting...
Data Saved for 2025-09-20 02:00:00 - Call: 123
Data is within range. Requesting...
Data Saved for 2025-09-20 22:00:00 - Call: 124
Data is within range. Requesting...
Data Saved for 2025-09-21 18:00:00 - Call: 125
Data is within range. Requesting...
Data Saved for 2025-09-22 14:00:00 - Call: 126
Data is within range. Requesting...
Data Saved for 2025-09-23 10:00:00 - Call: 127
Data is within range. Requesting...
Data Saved for 2025-09-24 06:00:00 - Call: 128
Data is within range. Requesting...
Data Saved for 2025-09-25 02:00:00 - Call: 129
Data is within range. Requesting...
Data Saved for 2025-09-25 22:00:00 - Call: 130
Data is within range. Requesting...
Data Saved for 2025-09-26 18:00:00 - Call: 131
Data is within range. Requesting...
Data Saved for 2025-09-27 14:00:00 - Call: 132
Data is within range. Requesting...
Data Saved for 2025-09-28 10:00:00 - Call: 133
Data is within range. Requesting...
Data Saved for 2025-09-29 06:00:00 - Call: 134
Data is within range. Requesting...
Data Saved for 2025-09-30 02:00:00 - Call: 135
Data is within range. Requesting...
Data Saved for 2025-09-30 22:00:00 - Call: 136
Data is within range. Requesting...
Data Saved for 2025-10-01 18:00:00 - Call: 137
Data is within range. Requesting...
Data Saved for 2025-10-02 14:00:00 - Call: 138
Data is within range. Requesting...
Data Saved for 2025-10-03 10:00:00 - Call: 139
Data is within range. Requesting...
Data Saved for 2025-10-04 06:00:00 - Call: 140
Data is within range. Requesting...
Data Saved for 2025-10-05 02:00:00 - Call: 141
Data is within range. Requesting...
Data Saved for 2025-10-05 22:00:00 - Call: 142
Data is within range. Requesting...
Data Saved for 2025-10-06 18:00:00 - Call: 143
Data is within range. Requesting...
Data Saved for 2025-10-07 14:00:00 - Call: 144
Data is within range. Requesting...
Data Saved for 2025-10-08 10:00:00 - Call: 145
Data is within range. Requesting...
Data Saved for 2025-10-09 06:00:00 - Call: 146
Data is within range. Requesting...
Data Saved for 2025-10-10 02:00:00 - Call: 147
Data is within range. Requesting...
Data Saved for 2025-10-10 22:00:00 - Call: 148
Data is within range. Requesting...
Data Saved for 2025-10-11 18:00:00 - Call: 149
Data is within range. Requesting...
Data Saved for 2025-10-12 14:00:00 - Call: 150
Data is within range. Requesting...
Data Saved for 2025-10-13 10:00:00 - Call: 151
Data is within range. Requesting...
Data Saved for 2025-10-14 06:00:00 - Call: 152
Data is within range. Requesting...
Data Saved for 2025-10-15 02:00:00 - Call: 153
Data is within range. Requesting...
Data Saved for 2025-10-15 22:00:00 - Call: 154
Data is within range. Requesting...
Data Saved for 2025-10-16 18:00:00 - Call: 155
Data is within range. Requesting...
Data Saved for 2025-10-17 14:00:00 - Call: 156
Data is within range. Requesting...
Data Saved for 2025-10-18 10:00:00 - Call: 157
Data is within range. Requesting...
Data Saved for 2025-10-19 06:00:00 - Call: 158
Data is within range. Requesting...
Data Saved for 2025-10-20 02:00:00 - Call: 159
Data is within range. Requesting...
Data Saved for 2025-10-20 22:00:00 - Call: 160
Data is within range. Requesting...
Data Saved for 2025-10-21 18:00:00 - Call: 161
Data is within range. Requesting...
Data Saved for 2025-10-22 14:00:00 - Call: 162
Data is within range. Requesting...
Data Saved for 2025-10-23 10:00:00 - Call: 163
Data is within range. Requesting...
Data Saved for 2025-10-24 06:00:00 - Call: 164
Data is within range. Requesting...
Data Saved for 2025-10-25 02:00:00 - Call: 165
Data is within range. Requesting...
Data Saved for 2025-10-25 22:00:00 - Call: 166
Data is within range. Requesting...
Data Saved for 2025-10-26 18:00:00 - Call: 167
Data is within range. Requesting...
Data Saved for 2025-10-27 14:00:00 - Call: 168
Data is within range. Requesting...
Data Saved for 2025-10-28 10:00:00 - Call: 169
Data is within range. Requesting...
Data Saved for 2025-10-29 06:00:00 - Call: 170
Data is within range. Requesting...
Data Saved for 2025-10-30 02:00:00 - Call: 171
Data is within range. Requesting...
Data Saved for 2025-10-30 22:00:00 - Call: 172
Data is within range. Requesting...
Data Saved for 2025-10-31 18:00:00 - Call: 173
Data is within range. Requesting...
Data Saved for 2025-11-01 14:00:00 - Call: 174
Data is within range. Requesting...
Data Saved for 2025-11-02 09:00:00 - Call: 175
Data is within range. Requesting...
Data Saved for 2025-11-03 05:00:00 - Call: 176
Data is within range. Requesting...
Data Saved for 2025-11-04 01:00:00 - Call: 177
Data is within range. Requesting...
Data Saved for 2025-11-04 21:00:00 - Call: 178
Data is within range. Requesting...
Data Saved for 2025-11-05 17:00:00 - Call: 179
Data is within range. Requesting...
Data Saved for 2025-11-06 13:00:00 - Call: 180
Data is within range. Requesting...
Data Saved for 2025-11-07 09:00:00 - Call: 181
Data is within range. Requesting...
Data Saved for 2025-11-08 05:00:00 - Call: 182
Data is within range. Requesting...
Data Saved for 2025-11-09 01:00:00 - Call: 183
Data is within range. Requesting...
Data Saved for 2025-11-09 21:00:00 - Call: 184
Data is within range. Requesting...
Data Saved for 2025-11-10 17:00:00 - Call: 185
Data is within range. Requesting...
Data Saved for 2025-11-11 13:00:00 - Call: 186
Data is within range. Requesting...
Data Saved for 2025-11-12 09:00:00 - Call: 187
Data is within range. Requesting...
Data Saved for 2025-11-13 05:00:00 - Call: 188
Data is within range. Requesting...
Data Saved for 2025-11-14 01:00:00 - Call: 189
Data is within range. Requesting...
Data Saved for 2025-11-14 21:00:00 - Call: 190
Data is within range. Requesting...
Data Saved for 2025-11-15 17:00:00 - Call: 191
Data is within range. Requesting...
Data Saved for 2025-11-16 13:00:00 - Call: 192
Data is within range. Requesting...
Data Saved for 2025-11-17 09:00:00 - Call: 193
Data is within range. Requesting...
Data Saved for 2025-11-18 05:00:00 - Call: 194
Data is within range. Requesting...
Data Saved for 2025-11-19 01:00:00 - Call: 195
Data is within range. Requesting...
Data Saved for 2025-11-19 21:00:00 - Call: 196
Data is within range. Requesting...
Data Saved for 2025-11-20 17:00:00 - Call: 197
Data is within range. Requesting...
Data Saved for 2025-11-21 13:00:00 - Call: 198
Data is within range. Requesting...
Data Saved for 2025-11-22 09:00:00 - Call: 199
Data is within range. Requesting...
Data Saved for 2025-11-23 05:00:00 - Call: 200
Data is within range. Requesting...
Data Saved for 2025-11-24 01:00:00 - Call: 201
Data is within range. Requesting...
Data Saved for 2025-11-24 21:00:00 - Call: 202
Data is within range. Requesting...
Data Saved for 2025-11-25 17:00:00 - Call: 203
Data is within range. Requesting...
Data Saved for 2025-11-26 13:00:00 - Call: 204
Data is within range. Requesting...
Data Saved for 2025-11-27 09:00:00 - Call: 205
Data is within range. Requesting...
Data Saved for 2025-11-28 05:00:00 - Call: 206
Data is within range. Requesting...
Data Saved for 2025-11-29 01:00:00 - Call: 207
Data is within range. Requesting...
Data Saved for 2025-11-29 21:00:00 - Call: 208
Data is within range. Requesting...
Data Saved for 2025-11-30 17:00:00 - Call: 209
Data is within range. Requesting...
Data Saved for 2025-12-01 13:00:00 - Call: 210
Data is within range. Requesting...
Data Saved for 2025-12-02 09:00:00 - Call: 211
Data is within range. Requesting...
Data Saved for 2025-12-03 05:00:00 - Call: 212
Data is within range. Requesting...
Data Saved for 2025-12-04 01:00:00 - Call: 213
Data is within range. Requesting...
Data Saved for 2025-12-04 21:00:00 - Call: 214
Data is within range. Requesting...
Data Saved for 2025-12-05 17:00:00 - Call: 215
Data is within range. Requesting...
Data Saved for 2025-12-06 13:00:00 - Call: 216
Data is within range. Requesting...
Data Saved for 2025-12-07 09:00:00 - Call: 217
Data is within range. Requesting...
Data Saved for 2025-12-08 05:00:00 - Call: 218
Data is within range. Requesting...
Data Saved for 2025-12-09 01:00:00 - Call: 219
Data is within range. Requesting...
Data Saved for 2025-12-09 21:00:00 - Call: 220
Data is within range. Requesting...
Data Saved for 2025-12-10 17:00:00 - Call: 221
Data is within range. Requesting...
Data Saved for 2025-12-11 13:00:00 - Call: 222
Data is within range. Requesting...
Data Saved for 2025-12-12 09:00:00 - Call: 223
Data is within range. Requesting...
Data Saved for 2025-12-13 05:00:00 - Call: 224
Data is within range. Requesting...
Data Saved for 2025-12-14 01:00:00 - Call: 225
Data is within range. Requesting...
Data Saved for 2025-12-14 21:00:00 - Call: 226
Data is within range. Requesting...
Data Saved for 2025-12-15 17:00:00 - Call: 227
Data is within range. Requesting...
Data Saved for 2025-12-16 13:00:00 - Call: 228
Data is within range. Requesting...
Data Saved for 2025-12-17 09:00:00 - Call: 229
Data is within range. Requesting...
Data Saved for 2025-12-18 05:00:00 - Call: 230
Data is within range. Requesting...
Data Saved for 2025-12-19 01:00:00 - Call: 231
Data is within range. Requesting...
Data Saved for 2025-12-19 21:00:00 - Call: 232
Data is within range. Requesting...
Data Saved for 2025-12-20 17:00:00 - Call: 233
Data is within range. Requesting...
Data Saved for 2025-12-21 13:00:00 - Call: 234
Data is within range. Requesting...
Data Saved for 2025-12-22 09:00:00 - Call: 235
Data is within range. Requesting...
Data Saved for 2025-12-23 05:00:00 - Call: 236
Data is within range. Requesting...
Data Saved for 2025-12-24 01:00:00 - Call: 237
Data is within range. Requesting...
Data Saved for 2025-12-24 21:00:00 - Call: 238
Data is within range. Requesting...
Data Saved for 2025-12-25 17:00:00 - Call: 239
Data is within range. Requesting...
Data Saved for 2025-12-26 13:00:00 - Call: 240
Data is within range. Requesting...
Data Saved for 2025-12-27 09:00:00 - Call: 241

In [8]:
weather_df = pd.DataFrame(records).drop_duplicates('dt').sort_values('dt').reset_index(drop=True)
weather_df = weather_df[weather_df['dt'] <= end]
weather_df['date'] = (pd.to_datetime(weather_df['dt'], unit='s', utc=True).dt.tz_convert('America/Los_Angeles'))

###FLATTEN weather data 
w = weather_df['weather'].str[0]
weather_df['weather_main'] = w.str['main']
weather_df['weather_desc'] = w.str['description']

for col in ['rain', 'snow']:
    if col in weather_df:
        weather_df[f'{col}_1hr_mm'] = weather_df[col].str['1h'].fillna(0)

weather_df = weather_df.drop(columns=[c for c in ['weather','rain','snow'] if c in weather_df])
weather_df.to_csv('scraped_data/weather.csv', index=False)

### Fuel Pricing Data

### Merging Bike and Weather Data, Visualizations

In [9]:
####Merge datasets to prepare to train model. 

bike_df
weather_df = pd.read_csv('scraped_data/weather.csv')

print('weather_df dates as a percent of bike_df dates:', '\nData Collected: {}%'.format(np.round(weather_df.shape[0]/bike_df.shape[0]*100,2)))

###set date column to datetime
weather_df.date = pd.to_datetime(weather_df.date, utc=True).dt.tz_convert('America/Los_Angeles')

df_merged = pd.merge(bike_df, weather_df, on='date')

print('Total observations in common: {}'.format(df_merged.shape[0]))

weather_df dates as a percent of bike_df dates:
Data Collected: 100.03%
Total observations in common: 121925